apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: validator-backend
  name: validator-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: validator-backend
  template:
    metadata:
      labels:
        app: validator-backend
    spec:
      containers:
      - name: validator-backend
        image: 992122884453.dkr.ecr.us-east-1.amazonaws.com/validator-backendend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP

# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: validator-backend
    k8s-app: validator-backend
  name: validator-backend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8081
  type: LoadBalancer
  selector:
    app: validator-backend
